### ISSUE TITLE
Login succeeds, video download fails on undefined method 'href'

### ISSUE THREAD

**Issue by roseperrone** [dennybritz/scpd-downloader#1]
./scpd_downloader.rb cs221 12 cs221-12.mp4
Downloading lecture 12 for course cs221
./scpd_downloader.rb:57:in `<main>': undefined method`href' for nil:NilClass (NoMethodError)

**Comment by dennybritz** [comment]
Hm, that happens if you give it a wrong lecture number. Are you sure the course had 12 videos? Does video 11 work?

**Comment by dennybritz** [comment]
I'm not sure why, but the CS221 course asked me to login twice, the other classes only once. This should work: 900bb3e3044bac31591b9e257bc9bef647bce0da
