### ISSUE TITLE
Two-step authentication code not getting sent

### ISSUE THREAD

**Issue by roseperrone** [dennybritz/scpd-downloader#2]
~/cloned_sources/scpd-downloader master ./scpd_downloader.rb cs221 11 cs221-12.mp4
Downloading lecture 11 for course cs221
SUNet ID: rdp
SUNet Password:
Logging in...
Two-step authentication code:

I tried disabling two-step auth, but then I couldn't access some materials in another class through the web interface. No text message gets sent to my phone via the above command.

**Comment by dennybritz** [comment]
Oh, I don't have text messages se tup, I use the Google authenticator app for two-step auth. Probably the web page for the text messages looks different. Do you need to click a button to send the message?

**Comment by roseperrone** [comment]
I set up Google Authenticator, and the download appeared to begin. Thank you!

**Comment by dennybritz** [comment]
Glad it worked :)

On Fri, Oct 25, 2013 at 3:14 PM, Rose Perrone notifications@github.comwrote:

> I set up Google Authenticator, and the download appeared to begin. Thank
> you!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/dennybritz/scpd-downloader/issues/2#issuecomment-27130100
> .

## 

Best,
Denny
