### ISSUE TITLE
CS140 request

### ISSUE THREAD

**Issue by techsmartteam** [dennybritz/scpd-downloader#3]
Thank you for contributing for the world a great script. I really need the videos of CS140 (Operating Systems). I have been seeking it for a long time without any luck. It would be greatly appreciated if you could please help me have access to the videos of Winter 2012 or Winter 2013. You're very lucky to be a Stanford graduate, is there any chance you know someone have downloaded this course?

**Comment by dennybritz** [comment]
Sorry, I don't know anyone, and sending the lectures around would be against the terms of service. But if you are looking for an Operating System course, why don't you check out CS162 from UC Berkeley, the videos are public here: http://www.youtube.com/watch?v=sjs5PtCsVA4&list=PL248F261B499CA858

The topics covered are very similar.

**Comment by techsmartteam** [comment]
Thank you for your swift reply. The material from Stanford is much understandable and the instructor Prof. John Ousterhout is the best. If you have any information about it, please send me some heads up. I really really appreciate it.
